using system
# char namespace: classification, case conversion, ascii round-trip
system.out.println(char.isalpha('a'))
system.out.println(char.isalpha('1'))
system.out.println(char.isdigit('7'))
system.out.println(char.isdigit('x'))
system.out.println(char.isupper('A'))
system.out.println(char.isupper('a'))
system.out.println(char.islower('z'))
system.out.println(char.islower('Z'))
system.out.println(char.isspace(' '))
system.out.println(char.isspace('x'))
system.out.println(char.isalnum('a'))
system.out.println(char.isalnum('9'))
system.out.println(char.isalnum('#'))
system.out.println(char.ispunct('#'))
system.out.println(char.tolower('Q'))
system.out.println(char.toupper('q'))
system.out.println(char.to_ascii('A'))
system.out.println(char.from_ascii(65))
system.out.println(char.from_ascii(97))
