system.out.println(math.constants.max)
system.out.println(math.constants.min)
system.out.println(math.constants.integer_max)
system.out.println(math.constants.integer_min)
system.out.println(math.constants.inf)
system.out.println(math.constants.nan)